name: Pipeline
on:
  push:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          pip install --user flake8
          pip install --user pylint
          flake8 main.py
          pylint main.py
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: python -m unittest --verbose --failfast
  store:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: python main.py
      - name: upload articfact
        uses: actions/upload-artifact@v3
        with:
          name: index
          path: ./build/index.html
  deploy:
    needs: store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: index
      - run: |
              http_code=$(curl -v --stderr deploy.log -w "%{http_code}\n" -F password=${{ secrets.PASSWORD }} -F file=@build/index.html -F user=${{ secrets.USER }} https://cs.uns.edu.ar/~jose.moyano/index.php)
              echo "$http_code" > http_code.txt
      - name: Guardar deploy-log
        uses: actions/upload-artifact@v3
        with:
          name: deploy-log
          path: ./deploy.log
      - name: Chequear code 200
        run: |
              if [ "$(cat http_code.txt)" -eq 200 ]; then
                echo "Exito"
              else
                echo "Error"
              fi
